# Generated by Django 5.1.7 on 2025-03-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(blank=True, max_length=255, null=True)),
                ('years_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('career_achievements', models.TextField(blank=True, null=True)),
                ('job_seeking', models.TextField(blank=True, null=True)),
                ('cv_challenges', models.TextField(blank=True, null=True)),
                ('interview_challenges', models.TextField(blank=True, null=True)),
                ('soft_skills', models.TextField(blank=True, null=True)),
                ('career_goals', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_profile_summary', models.TextField(blank=True, null=True)),
                ('cv_recommendations', models.TextField(blank=True, null=True)),
                ('interview_tips', models.TextField(blank=True, null=True)),
                ('skill_development_plan', models.TextField(blank=True, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='api.questionnaireresponse')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='api.user'),
        ),
    ]
